language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh && chmod +x .travis-docker.sh
script: ./.travis-docker.sh
services:
- docker
env:
  global:
  - PINS="ranger:."
  - DISTRO="ubuntu-16.04"
  - PACKAGE="ranger"
  matrix:
  - OCAML_VERSION="4.02"
  - OCAML_VERSION="4.03"
  - OCAML_VERSION="4.04"
  - OCAML_VERSION="4.05"
  - OCAML_VERSION="4.06"
  - OCAML_VERSION="4.07"
  - OCAML_VERSION="4.08"
  - OCAML_VERSION="4.09"
